# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc8259bc1c769962b64bcef7fafe942e9784756625573826d384103b9a1966add1c21720b024c65f92e35898ef60712a0e16a95c4e1844e22f19cd247e7654c
  consumer_key: <%= ENV["UNASUKE_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["UNASUKE_CONSUMER_SECRET"] %>
  access_token: <%= ENV["UNASUKE_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["UNASUKE_ACCESS_TOKEN_SECRET"] %>

test:
  secret_key_base: 9946c24ad4695e20f70c1dfb33862eb7a0267a1cd9cf9426048cbcd8e3d1d0760cf174f8ad47b7b8c17ef0d922d340e8433c467a743ad0648d87700bdded0b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
